site_name: relic
docs_dir: doc
nav:
  - Intro: index.md
  - Query:
    - Overview: query.md
    - Issuing queries: query.md
    - Expressions: expr.md
    - Query statements:
      - :agg: agg.md
      - :const: const.md
      - :from: from.md
      - :difference: difference.md
      - :expand: expand.md
      - :extend: extend.md
      - :from: from.md
      - :intersection: intersection.md
      - :join: join.md
      - :left-join: left-join.md
      - :qualify: qualify.md
      - :rename: rename.md
      - :select: select.md
      - :union: union.md
      - :where: where.md
      - :without: without.md
    - Indexes:
      - Overview: indexes.md
      - :btree: btree.md
      - :hash: hash.md
      - :lookup: lookup.md
    - Aggregates: aggregates.md
    - Aggregate functions:
      - Stats:
         - max: max.md
         - max-by: max-by.md
         - min: min.md
         - min-by: min-by.md
         - avg: avg.md
      - Counts:
         - count: count.md
         - count-distinct: count-distinct.md
      - "Top/Bottom N":
         - top: top.md
         - top-by: top-by.md
         - bottom: bottom.md
         - bottom-by: bottom-by.md
      - sum: sum.md
      - any: any.md
      - not-any: not-any.md
      - set-concat: set-concat.md
    - Sub queries: sub-queries.md
    - Unsafe transforms: unsafe-transform.md
  - Transactions:
    - transact: transact.md
    - :insert: insert.md
    - :delete: delete.md
    - :delete-exact: delete-exact.md
    - :update: update.md
    - :insert-or-replace: insert-or-replace.md
    - :replace-all: replace-all.md
    - Terse Inserts: terse-insert.md
  - Materialization: materialization.md
  - Change tracking: change-tracking.md
  - Environment: env.md
  - Constraints:
    - Overview: constraints.md
    - :check: check.md
    - :fk: fk.md
    - :req: req.md
    - :unique: unique.md
    - :constrain: constrain.md
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
repo_url: https://github.com/wotbrew/relic
edit_uri: edit/master/doc/